### ISSUE TITLE
Fix h1 and h2 visual sizing

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#1]
h1 rendered smaller than h2s. They should decrease visually in size.

**Comment by klepas** [comment]
How do we wanna do this? We styled these according to the design direction of @gazhands and Alz.

I did a quick switcheroo of `h1`↔`h2` and the results aren’t great since our h3s are the same size as our `h2`s now **and** bold — see screenshots:

![screen shot 2017-03-06 at 2 09 13 pm](https://cloud.githubusercontent.com/assets/52766/23595555/d9c38274-0276-11e7-8980-362c47dcbaf1.png)

![screen shot 2017-03-06 at 2 09 47 pm](https://cloud.githubusercontent.com/assets/52766/23595556/dd51b410-0276-11e7-8f32-1ae3699ee978.png)

Also, our `.abstract` text now is the same size and style as our `h2`s:

![screen shot 2017-03-06 at 2 09 36 pm](https://cloud.githubusercontent.com/assets/52766/23595561/ef76eade-0276-11e7-837a-2f98643f9f66.png)

***

@gazhands Let’s have a chat? (:

**Comment by gazhands** [comment]
Any tweaks to H1 / H2 will be picked up in the Federated Design clinic and checked with all product teams. Plan is to update UI Kit with refined font styling.

**Comment by joolswood** [comment]
@gazhands @klepas We could fix this for the Content Guide without affecting any one else's product. We could use this guide as a way to test and find some good new font sizes that can be run by other teams - much easier than asking them to consider something without seeing a real full site example.

Currently we have a horrible situation, thus:
![screen shot 2017-03-07 at 9 18 45 am](https://cloud.githubusercontent.com/assets/13774080/23632794/5fa9c740-0317-11e7-9640-aad94386a0f5.png)

**Comment by klepas** [comment]
Fixed in above PR.
