### ISSUE TITLE
Faces in photos

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#39]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/116

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/accessibility-inclusivity/#images-alt-text

**Comment by gazanson** [comment]
Not sure I understand this. Need more background to progress.

**Comment by joolswood** [comment]
Does this help? https://github.com/AusDTO/gov-au-content-guide/issues/116

**Comment by gazanson** [comment]
See suggested write up here: https://docs.google.com/document/d/1mnkOQCR-FhziM3-bWFRYJogjjzUBVGgzCbZu9YBT4cA/edit?disco=AAAABT6Qljw

**Comment by gazanson** [comment]
Suggested write up -- Gary A. But waiting for input from Andrew Arch's replacement ...

--------------------------------------

http://content-guide.apps.staging.digital.gov.au/accessibility-inclusivity/#images-and-alt-text

[insert after ‘Informative images’ topic]

Photos of faces

When inserting a photo of a person on a page, place the image so that the person's face and eyes are looking towards the content on the page. If the person is looking away from the content, a user might miss important content as they will tend, unconsciously, to look in the direction the image of the person is looking.

**Comment by gazanson** [comment]
Now being tracked in Trello
